FROM python:3.12-slim

WORKDIR /app
ARG CACHE_BUST

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/src

EXPOSE 5000
CMD ["gunicorn", "--reload", "-w", "1", "-b", "0.0.0.0:5000", "app:app"]
