version: "3.8"
name: local-seaglass-dev

services:
  seaglass:
    build:
      context: ../.
      dockerfile: ./containerfiles/Containerfile.dev
    container_name: seaglass-dev
    ports:
      - "5000:5000"
    environment:
      - TRANSFLUX_URL=http://api.transcode.spacesaver.lan
      - BRINECRYPT_URL=http://brinecrypt.lan
    dns:
      - 192.168.0.127
    volumes:
      - ../src:/app/src:Z
      - ../requirements.txt:/app/requirements.txt:Z
    working_dir: /app/src
    command:
      ["gunicorn", "--reload", "-w", "1", "-b", "0.0.0.0:5000", "app:app"]
    restart: unless-stopped
